# Generated by Django 4.1.2 on 2022-10-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_cover', '0002_rename_name_bookcover_type_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=40, verbose_name='Название книги')),
                ('type_cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_cover.bookcover', verbose_name='Тип обложки')),
            ],
        ),
    ]
