# Generated by Django 4.1.2 on 2022-10-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_reference', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=40, verbose_name='Название книги')),
                ('book_author', models.ManyToManyField(to='book_reference.bookauthor', verbose_name='Автор')),
                ('book_genre', models.ManyToManyField(to='book_reference.bookgenre', verbose_name='Жанр')),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_reference.bookpublisher', verbose_name='Издательство')),
                ('book_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_reference.bookseries', verbose_name='Серия')),
            ],
        ),
    ]
