# Generated by Django 4.1.2 on 2022-10-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0003_remove_bookseries_book_publisher_and_more'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_reference.bookseries', verbose_name='Серия'),
        ),
    ]
