# Generated by Django 4.1.2 on 2022-10-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_dop',
            field=models.CharField(default=1, max_length=40, verbose_name='ДОп'),
            preserve_default=False,
        ),
    ]
