# Generated by Django 4.1.2 on 2022-10-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_series',
        ),
    ]
