# Generated by Django 4.1.2 on 2022-10-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0005_bookseries'),
        ('book', '0003_remove_book_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book_reference.bookseries', verbose_name='Серия'),
            preserve_default=False,
        ),
    ]
