# Generated by Django 4.1.2 on 2022-10-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_book_dop'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Цена (BYN)'),
            preserve_default=False,
        ),
    ]
