# Generated by Django 4.1.2 on 2022-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена (BYN)'),
        ),
    ]
