# Generated by Django 4.1.2 on 2022-10-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0006_bookauthor'),
        ('book', '0004_book_book_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_reference.bookseries', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(to='book_reference.bookgenre', verbose_name='Жанр'),
        ),
    ]
