# Generated by Django 4.1.2 on 2022-10-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0006_bookauthor'),
        ('book', '0005_remove_book_book_genre_alter_book_book_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(to='book_reference.bookauthor', verbose_name='Автор'),
        ),
    ]
