# Generated by Django 4.1.2 on 2022-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_book_active_alter_book_book_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_active',
            field=models.CharField(choices=[(1, 'Да'), (2, 'Нет')], default='Да', max_length=5, verbose_name='Активный (доступен для заказа)'),
            preserve_default=False,
        ),
    ]
