# Generated by Django 4.1.2 on 2022-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookyear',
            name='book_year',
            field=models.CharField(max_length=40, verbose_name='Год'),
        ),
    ]
