# Generated by Django 4.1.2 on 2022-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_publisher', models.CharField(blank=True, max_length=40, null=True, verbose_name='Серия')),
            ],
        ),
    ]
