# Generated by Django 4.1.2 on 2022-11-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookauthor',
            old_name='book_author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookgenre',
            old_name='book_genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookpublisher',
            old_name='book_publisher',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookseries',
            old_name='book_series',
            new_name='name',
        ),
    ]
