# Generated by Django 4.1.2 on 2022-10-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0002_bookseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='book_publisher',
        ),
        migrations.AddField(
            model_name='bookseries',
            name='book_series',
            field=models.CharField(default=1, max_length=40, verbose_name='Серия'),
            preserve_default=False,
        ),
    ]
