# Generated by Django 4.1.2 on 2022-11-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0002_rename_book_author_bookauthor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание жанра'),
        ),
    ]
