# Generated by Django 4.1.2 on 2022-12-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reference', '0003_alter_bookgenre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='name_lower',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='Автор'),
        ),
    ]
