# Generated by Django 4.1.2 on 2022-10-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_book_series'),
        ('book_reference', '0003_remove_bookseries_book_publisher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSeries',
        ),
    ]
