# Generated by Django 4.1.2 on 2022-11-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
