# Generated by Django 4.1.2 on 2022-11-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_group',
        ),
    ]
