# Generated by Django 4.1.2 on 2022-11-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('заказ принят', 'Заказ принят'), ('заказ собран', 'Заказ собран'), ('заказ отправлен', 'Заказ отправлен'), ('заказ доставлен', 'Заказ доставлен')], max_length=200, verbose_name='Статус')),
                ('last_first_name', models.TextField(verbose_name='Фамилия Имя:')),
                ('email', models.TextField(verbose_name='E-mail:')),
                ('adress', models.TextField(verbose_name='Адрес достаки:')),
                ('phone_number', models.TextField(verbose_name='Номер телефона:')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.cart', verbose_name='Cart')),
            ],
        ),
    ]
