# Generated by Django 4.1.2 on 2022-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('заказ принят', 'Заказ принят'), ('заказ собран', 'Заказ собран'), ('заказ отправлен', 'Заказ отправлен'), ('заказ доставлен', 'Заказ доставлен')], default='заказ принят', max_length=200, verbose_name='Статус'),
        ),
    ]
