# Generated by Django 4.1.2 on 2022-12-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Адрес достаки:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_first_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия Имя:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Номер телефона:'),
        ),
    ]
