# Generated by Django 4.1.2 on 2022-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_adress_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Заказ принят'), ('collected', 'Заказ собран'), ('sent', 'Заказ отправлен'), ('deliver', 'Заказ доставлен')], default='Заказ принят', max_length=200, verbose_name='Статус'),
        ),
    ]
