# Generated by Django 4.1.2 on 2022-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='information',
            field=models.TextField(default=1, verbose_name='Дополнительная информация:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail:'),
        ),
    ]
