# Generated by Django 4.1.2 on 2022-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_information_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация:'),
        ),
    ]
